---
- name: enable ospf
  cisco.nxos.nxos_feature:
    feature: ospf
    state: enabled

- name: enable bgp
  cisco.nxos.nxos_feature:
    feature: bgp
    state: enabled

- name: enable vn-segment-vlan-based
  cisco.nxos.nxos_feature:
    feature: vn-segment-vlan-based
    state: enabled

- name: enable nv overlay
  cisco.nxos.nxos_feature:
    feature: nv overlay
    state: enabled

- name: enable pim
  cisco.nxos.nxos_feature:
    feature: pim
    state: enabled